-- TB_ADDRESS 데이터 삽입
INSERT INTO TB_ADDRESS (PROVINCE, CITY, DISTRICT, TOWN) VALUES ( '서울특별시', '', '마포구', '연남동');
INSERT INTO TB_ADDRESS (PROVINCE, CITY, DISTRICT, TOWN) VALUES ( '서울특별시', '', '종로구', '평창동');

-- TB_CATEGORY_GROUP 데이터 삽입
INSERT INTO TB_CATEGORY_GROUP (CATEGORY_GROUP_ID, CATEGORY_GROUP_NAME, POST_TYPE) VALUES (1, '강아지', 'REHOMING');

-- TB_PET_CATEGORY 데이터 삽입
INSERT INTO TB_PET_CATEGORY (PET_CATEGORY_ID, PET_CATEGORY_NAME, CATEGORY_GROUP_ID) VALUES (1, '고든 세터', 1);

-- TB_TRADE_CATEGORY 데이터 삽입
INSERT INTO TB_TRADE_CATEGORY (TRADE_CATEGORY_ID, TRADE_CATEGORY_NAME, CATEGORY_GROUP_ID) VALUES (1, '강아지 사료', 4);

-- TB_TRADE_CATEGORY_DETAIL 데이터 삽입
INSERT INTO TB_TRADE_CATEGORY_DETAIL (TRADE_CATEGORY_DETAIL_ID, TRADE_CATEGORY_DETAIL_NAME, TRADE_CATEGORY_ID) VALUES (1, '건식 사료', 1);

